/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './navbar/navbar.component.ngfactory';
import * as i3 from './navbar/navbar.component';
import * as i4 from '@angular/router';
import * as i5 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'navbar',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_NavbarComponent_0,i2.RenderType_NavbarComponent)),
      i1.ɵdid(1,114688,(null as any),0,i3.NavbarComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(3,
          0,(null as any),(null as any),4,'div',[['class','container']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵeld(5,16777216,(null as any),(null as any),
          1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),i1.ɵdid(6,212992,(null as any),0,i4.RouterOutlet,
          [i4.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,6,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i5.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i5.AppComponent> = i1.ɵccf('app-root',
    i5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQW5ndWxhci9kZXBsb3ltZW50L2RlcGxveS1kZW1vL2RlcGxveS1kZW1vL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Bbmd1bGFyL2RlcGxveW1lbnQvZGVwbG95LWRlbW8vZGVwbG95LWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovQW5ndWxhci9kZXBsb3ltZW50L2RlcGxveS1kZW1vL2RlcGxveS1kZW1vL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovQW5ndWxhci9kZXBsb3ltZW50L2RlcGxveS1kZW1vL2RlcGxveS1kZW1vL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bmF2YmFyPjwvbmF2YmFyPlxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG48L2Rpdj4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUEsZUFBaUIsMENBQ2pCO1VBQUE7VUFBQSwwREFBdUI7VUFBQSx5QkFDckI7VUFBQTtVQUFBLHFDQUFBO1VBQUE7Y0FBQTtNQUErQjtJQUZqQztJQUVFOzs7O29CQ0ZGO01BQUE7YUFBQTtVQUFBOzs7In0=
